### ISSUE TITLE
Save doesn't work as implied by gui design

### ISSUE THREAD

**Issue by ghost** [Love-Ivy/ILW5Schedule#1]
By the number of save buttons and how there's one next to each hour container I would expect them to only save the content of that container. Instead they each behave identically and save all containers on the app.

**Comment by Love-Ivy** [comment]
This was a problem with Firefox. Each time block is saved in local storage with a unique key. On load, javascript runs through each time block and checks that key for data. If the data is null, it does nothing and checks the next field.
Firefox was saving this data independently of my code. The javascript was working as intended, and empty fields still contained no data in local storage, but Firefox would keep those fields populated regardless. I don't know where they have this data.

Javascript will now clear time block values if local storage is null.
